# Numpy 
Numpy is a general-purpose array processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python

### What is an array
An array is a data structure that stores values of same data type. In python this is the main difference between arrays and llist. While python lists can contain values corresponding to different data types, arrays in python can only contains values corresponding to same data type

In [1]:
#lets import numpy libraries

import numpy as np

In [2]:
list1=[1,2,3,4,5]
arr=np.array(list1)  #one dimensional array

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [8]:
## for converting one dimensional to multidimensional array
## Multi dimensional array

list1=[1,2,3,4,5]
list2=[6,7,8,8,9]
arr=np.array([list1,list2])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 8, 9]])

In [10]:
arr.shape

(2, 5)

In [11]:
#for changing the dimension

arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [8, 9]])

In [13]:
arr.reshape(1,5)       #in reshaping it should same values

ValueError: cannot reshape array of size 10 into shape (1,5)

## Indexing

In [14]:
## Accessing the array elements

arr=np.array([1,2,3,4,5])

In [20]:
arr[4]

5

In [21]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [22]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [23]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [25]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [26]:
arr[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [29]:
arr[1:,3:]

array([[9, 0]])

In [31]:
# arrange
# create one dimensional array with specified values
# np.arange(start,stop,step)
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [34]:
# linspace function
# between start and stop how many values you can want

arr=np.linspace(0,10,num=20)
arr


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [35]:
arr.size

20

In [36]:
## copy function / broadcasting

arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [38]:
arr1=arr
arr1[3:]=500
arr,arr1

(array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500]),
 array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500]))

In [40]:
arr2=arr1.copy()
arr2[3:]=1000
arr1,arr2

(array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500]),
 array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000]))

In [41]:
## Some conditions very useful iin Exploratory data analysis

val=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [42]:
arr*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [43]:
arr[arr<2]

array([0, 1])

In [45]:
arr[arr>2]

array([500, 500, 500, 500, 500, 500, 500])

In [46]:
## ones function
# create 1s

np.ones(4)

array([1., 1., 1., 1.])

In [49]:
np.ones(shape=(2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
## random distribution
# creates values randomly from 0 to 1

np.random.rand(3,3)

array([[0.56975602, 0.79561404, 0.43187251],
       [0.42605977, 0.43356617, 0.41613001],
       [0.86445127, 0.33025118, 0.72504717]])

In [51]:
## random distribution with randn
# selects values based on standard normal distribution

np.random.randn(3,3)

array([[ 0.96336378, -1.71655348,  0.15040178],
       [ 0.77304503,  0.72088773, -0.82255042],
       [-1.86353818,  0.36655879,  0.12689349]])

In [54]:
## random distribution with randint
# gives random int values

np.random.randint(low=0,high=10,size=(3,3))

array([[4, 3, 6],
       [3, 9, 7],
       [0, 4, 4]])

In [55]:
## random sample

np.random.random_sample(8)

array([0.98771661, 0.31574215, 0.14607015, 0.8527627 , 0.19445368,
       0.640167  , 0.84700805, 0.97291214])